/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCopilotkitSplatRouteImport } from './routes/api/copilotkit.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotkitSplatRoute = ApiCopilotkitSplatRouteImport.update({
  id: '/api/copilotkit/$',
  path: '/api/copilotkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/copilotkit/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/copilotkit/$'
  id: '__root__' | '/' | '/api/copilotkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCopilotkitSplatRoute: typeof ApiCopilotkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilotkit/$': {
      id: '/api/copilotkit/$'
      path: '/api/copilotkit/$'
      fullPath: '/api/copilotkit/$'
      preLoaderRoute: typeof ApiCopilotkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCopilotkitSplatRoute: ApiCopilotkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
